redirectsOrigin = "config"
plugins = []
headers = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\chandrasekhar.g\\Desktop\\kncci-internship-10-03\\kncciinternship_ui\\dist\\Lmsapp"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"

[build.environment]
NODE_VERSION = "18"
NODE_OPTIONS = "--openssl-legacy-provider --max_old_space_size=6048"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]